### ISSUE TITLE
Limited amount of nodes in mesh network?

### ISSUE THREAD

**Issue by vannimb** [nootropicdesign/lora-mesh#2]
Hello,
I see in LoRaMesh.ino the following lines:
  nodeId = EEPROM.read(0);
  if (nodeId > 10) {
    Serial.print(F("EEPROM nodeId invalid: "));
    Serial.println(nodeId);
    nodeId = 1;
  }

does this means that the mesh network size is limited to 10 units maximum including the gateway?

If this is the case, is there a reason for this limit?

**Comment by noeldum** [comment]
I second the question. What is the max number of nodes in Radiohead?

nodeid is defined as uint8_t. Does this means we are limited to 256 nodes?

**Comment by nootropicdesign** [comment]
This particular demonstration supports 10 nodes, but I've only tried 4. More nodes means constant collision on the airwaves, depending on how often a node transmits. The RadioHead library supports only 255 nodes, per the 8 bit value. I don't think 0 is a valid node number.
