### ISSUE TITLE
Security of Lora Mesh Network

### ISSUE THREAD

**Issue by mightChamp** [nootropicdesign/lora-mesh#6]
Hello,
I want to know about data security in Lora Mesh Network, is it encrypted?
And How can I used two or more different Lora Mesh network at same place, like zigbee ?

Thank You

**Comment by nootropicdesign** [comment]
LoRa communications are encrypted. This is not an issue for this code repository.
To use multiple LoRa mesh networks in the same location, you would need to alter the addressing scheme.
