### ISSUE TITLE
Is Lora Mesh Will Follow Duty Cycle Regulations

### ISSUE THREAD

**Issue by mightChamp** [nootropicdesign/lora-mesh#7]
Hello,

As a Lora node may have transmit more for neighbor nodes, which may be higher than 1% of duty cycle. 
Is Lora Mesh Follow regulations like duty cycle of 1%, etc. as it follow in LoraWAN.

Thank You

**Comment by nootropicdesign** [comment]
This project does not use LoRaWAN technology. Just point-to-point LoRa radio communication. Please don't open issues on GitHub to ask questions. Use the project website.
