### ISSUE TITLE
diagram of esp32 with lora

### ISSUE THREAD

**Issue by Vibeesarma** [nootropicdesign/lora-mesh#9]
can anyone tell the circuit diagram of esp32 with Lora connection for this mesh code?

**Comment by nootropicdesign** [comment]
This is not a defect. Please understand that this project is NOT for ESP32.

**Comment by Vibeesarma** [comment]
is it possible to work on for Arduino Uno?

**Comment by nootropicdesign** [comment]
The project uses Moteino boards which have an ATmega328 microcontroller just like the Arduino Uno. See the project article: https://nootropicdesign.com/projectlab/2018/10/20/lora-mesh-networking/
